"""
Email delivery via Resend.

Two send functions:
  send_review_email  — content generated, sent to operator for review
  send_delivery_email — content approved, sent to client
"""
from __future__ import annotations

import os
import re
from dotenv import load_dotenv

load_dotenv()

import resend

resend.api_key = os.environ.get("RESEND_API_KEY", "").strip()

FROM_ADDRESS = os.environ.get("FROM_EMAIL", "Said By <onboarding@resend.dev>")
OPERATOR_EMAIL = os.environ.get("OPERATOR_EMAIL", "").strip()
REVIEW_UI_URL = os.environ.get("REVIEW_UI_URL", "http://localhost:8502").strip()


def _md_to_html(text: str) -> str:
    """Minimal markdown → HTML for email bodies (headings, bold, paragraphs)."""
    lines, html = text.splitlines(), []
    for line in lines:
        line = line.rstrip()
        if line.startswith("### "):
            html.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html.append(f"<h1>{line[2:]}</h1>")
        elif line == "":
            html.append("<br/>")
        else:
            line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            line = re.sub(r"\*(.+?)\*", r"<em>\1</em>", line)
            html.append(f"<p>{line}</p>")
    return "\n".join(html)


def _base_style() -> str:
    return """
    <style>
      body { font-family: Georgia, serif; max-width: 680px; margin: 0 auto; padding: 32px 24px; color: #1f2937; }
      h1 { font-size: 1.6rem; margin-bottom: 0.5rem; }
      h2 { font-size: 1.3rem; margin-top: 1.5rem; }
      h3 { font-size: 1.1rem; margin-top: 1.2rem; }
      p  { line-height: 1.7; margin: 0.6rem 0; }
      .meta { font-size: 0.8rem; color: #6b7280; margin-bottom: 2rem; border-bottom: 1px solid #e5e7eb; padding-bottom: 1rem; }
      .banner { background: #eef2ff; border: 1px solid #c7d2fe; border-radius: 6px; padding: 16px 20px; margin-bottom: 2rem; }
      .banner a { color: #4f46e5; font-weight: 600; }
      .content { border-top: 2px solid #e5e7eb; padding-top: 1.5rem; margin-top: 1.5rem; }
      .footer { font-size: 0.75rem; color: #9ca3af; margin-top: 3rem; border-top: 1px solid #f3f4f6; padding-top: 1rem; }
    </style>
    """


def send_review_email(
    *,
    client_name: str,
    client_brand_id: str,
    topic_title: str,
    content_markdown: str,
    slot_type: str = "long_blog",
) -> str:
    """Send generated content to the operator for review. Returns Resend message ID."""
    if not OPERATOR_EMAIL:
        raise ValueError("OPERATOR_EMAIL is not set in .env")

    topic_title = " ".join(topic_title.split())  # collapse any whitespace/newlines
    content_type = "Long blog" if slot_type == "long_blog" else "Short snippet"
    html_content = _md_to_html(content_markdown)

    html = f"""
    <!DOCTYPE html><html><head>{_base_style()}</head><body>
    <div class="banner">
      ✦ New content ready for review — <strong>{client_name}</strong><br/>
      <small>Log in to approve or reject: <a href="{REVIEW_UI_URL}">{REVIEW_UI_URL}</a></small>
    </div>
    <div class="meta">
      <strong>Client:</strong> {client_name} &nbsp;·&nbsp;
      <strong>Type:</strong> {content_type} &nbsp;·&nbsp;
      <strong>Brand:</strong> {client_brand_id}
    </div>
    <h1>{topic_title}</h1>
    <div class="content">
      {html_content}
    </div>
    <div class="footer">
      Generated by Content Factory · Reply to this email or visit the UI to approve.
    </div>
    </body></html>
    """

    params: resend.Emails.SendParams = {
        "from": FROM_ADDRESS,
        "to": [OPERATOR_EMAIL],
        "subject": f"[Review] {topic_title} — {client_name}",
        "html": html,
    }
    response = resend.Emails.send(params)
    return response["id"]


def send_welcome_email(*, brand: dict, topics: list[str]) -> str:
    """Send welcome email to client with their approved topic list."""
    if not OPERATOR_EMAIL:
        raise ValueError("OPERATOR_EMAIL is not set in .env")

    client_name = brand.get("client_name") or brand.get("brand_id", "")
    first_name = client_name.split()[0] if client_name else "there"
    client_email = brand.get("client_email", "")
    if not client_email:
        raise ValueError("client_email not set on brand profile")

    sandbox = "resend.dev" in FROM_ADDRESS
    to_address = OPERATOR_EMAIL if sandbox else client_email

    slots = brand.get("content_slots", [])
    cadence = brand.get("cadence", {})
    freq = cadence.get("publication_cadence", "weekly")
    freq_label = "twice a week" if freq == "twice_weekly" else "once a week"
    days = [s.get("day", "").capitalize() for s in slots]
    days_label = " and ".join(days) if days else "your scheduled days"
    package_size = brand.get("package_size", 8)

    # Pull niche + audience for personalisation
    about = ((brand.get("topic_policy") or {}).get("allowlist") or [""])[0]
    audience_ctx = (brand.get("audience") or {}).get("audience_context", "")

    # Build topics list — clean quotes before rendering
    def clean(t: str) -> str:
        return t.replace('‘', "'").replace('’', "'").replace('“', '"').replace('”', '"')

    topics_html = "".join(
        f'<li style="margin:0.6rem 0;color:#374151;line-height:1.5">{clean(t)}</li>'
        for t in topics
    )

    # Personalised intro line based on what they write about
    niche_line = ""
    if about:
        niche_line = f'<p style="color:#4b5563;font-style:italic;border-left:3px solid #6366f1;padding-left:1rem;margin:1.5rem 0">{clean(about)}</p>'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width"/>
  <style>
    body {{ font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 40px 24px; color: #1f2937; line-height: 1.8; background: #fff; }}
    h1 {{ font-size: 1.5rem; font-weight: 700; margin-bottom: 0.25rem; color: #111827; }}
    p {{ margin: 1rem 0; font-size: 1rem; }}
    ol {{ padding-left: 1.25rem; margin: 1.5rem 0; }}
    strong {{ color: #111827; }}
    .divider {{ border: none; border-top: 1px solid #e5e7eb; margin: 2rem 0; }}
    .footer {{ font-size: 0.75rem; color: #9ca3af; margin-top: 3rem; }}
    .badge {{ display: inline-block; background: #eef2ff; color: #4338ca; font-size: 0.75rem; font-weight: 600; padding: 0.2rem 0.6rem; border-radius: 999px; font-family: sans-serif; letter-spacing: 0.05em; text-transform: uppercase; }}
  </style>
</head>
<body>
  <p><span class="badge">Said By</span></p>

  <h1>{first_name} — you're in.</h1>

  <p>We've reviewed your submission and we want to be direct: <strong>this is exactly the kind of work we love doing.</strong></p>

  {niche_line}

  <p>Your voice, your audience{f', your focus on {audience_ctx}' if audience_ctx else ''} — it's a compelling brief. And we're ready to run with it.</p>

  <hr class="divider"/>

  <p><strong>Here's your content plan — {package_size} articles:</strong></p>

  <ol>{topics_html}</ol>

  <p>These will go out <strong>{freq_label}</strong>, every <strong>{days_label}</strong>. Each piece written in your voice, sent to you for approval before it goes anywhere.</p>

  <hr class="divider"/>

  <p><strong>Ready to get started?</strong></p>
  <p>Simply reply to this email to confirm and we'll kick things off. The first article will be in your inbox before you know it.</p>

  <p style="margin-top:2.5rem">We're genuinely excited about this one.</p>

  <p>— Jiraindira<br/><span style="color:#9ca3af;font-size:0.9rem">Said By</span></p>

  <div class="footer">Said By · <a href="{REVIEW_UI_URL}" style="color:#6366f1">{REVIEW_UI_URL}</a></div>
</body>
</html>"""

    subject = f"{first_name} — your content plan is confirmed"
    if sandbox:
        subject = f"[SANDBOX → {client_email}] {subject}"

    params: resend.Emails.SendParams = {
        "from": FROM_ADDRESS,
        "to": [to_address],
        "subject": subject,
        "html": html,
    }
    response = resend.Emails.send(params)
    return response["id"]


def send_new_submission_email(*, submission: dict) -> str:
    """Notify operator that a new client intake was submitted."""
    if not OPERATOR_EMAIL:
        raise ValueError("OPERATOR_EMAIL is not set in .env")

    name = submission.get("client_name", "Unknown")
    email = submission.get("client_email", "")
    role = submission.get("brand_archetype", "").replace("_", " ").title()
    about = submission.get("about", "")
    review_url = f"{REVIEW_UI_URL}/admin"

    html = f"""
    <!DOCTYPE html><html><head>{_base_style()}</head><body>
    <div class="banner">
      ✦ New client intake submitted<br/>
      <small>Review and activate at: <a href="{review_url}">{review_url}</a></small>
    </div>
    <h2 style="margin-top:0">{name}</h2>
    <div class="meta">
      <strong>Email:</strong> {email} &nbsp;·&nbsp;
      <strong>Role:</strong> {role}
    </div>
    <p><strong>What they write about:</strong><br/>{about}</p>
    <div class="footer">Content Factory · New submission notification</div>
    </body></html>
    """

    params: resend.Emails.SendParams = {
        "from": FROM_ADDRESS,
        "to": [OPERATOR_EMAIL],
        "subject": f"New intake: {name}",
        "html": html,
    }
    response = resend.Emails.send(params)
    return response["id"]


def send_delivery_email(
    *,
    client_name: str,
    client_email: str,
    topic_title: str,
    content_markdown: str,
    slot_type: str = "long_blog",
) -> str:
    """Send approved content to the client. Returns Resend message ID.

    In sandbox mode (no custom domain), Resend only allows sending to the
    operator's own address. We route there with a forwarding note.
    """
    if not client_email:
        raise ValueError("client_email is empty")

    topic_title = " ".join(topic_title.split())
    # Sandbox = still on resend.dev address; custom domain = send direct to client
    sandbox = "resend.dev" in FROM_ADDRESS
    to_address = OPERATOR_EMAIL if sandbox else client_email
    html_content = _md_to_html(content_markdown)

    sandbox_banner = ""
    if sandbox:
        sandbox_banner = f"""
        <div style="background:#fef3c7;border:1px solid #fcd34d;border-radius:6px;padding:12px 16px;margin-bottom:24px;font-size:0.8rem;color:#92400e;">
          <strong>Sandbox mode</strong> — This would be sent to <strong>{client_email}</strong>.
          Forward manually or verify a domain at resend.com/domains to send directly.
        </div>"""

    html = f"""
    <!DOCTYPE html><html><head>{_base_style()}</head><body>
    {sandbox_banner}
    <h1>{topic_title}</h1>
    <div class="content">
      {html_content}
    </div>
    <div class="footer">
      Delivered by Content Factory · For: {client_name} ({client_email})
    </div>
    </body></html>
    """

    params: resend.Emails.SendParams = {
        "from": FROM_ADDRESS,
        "to": [to_address],
        "subject": f"[{client_name}] {topic_title}" if sandbox else topic_title,
        "html": html,
    }
    response = resend.Emails.send(params)
    return response["id"]
