"""
Email delivery via Resend.

Two send functions:
  send_review_email  — content generated, sent to operator for review
  send_delivery_email — content approved, sent to client
"""
from __future__ import annotations

import os
import re
from dotenv import load_dotenv

load_dotenv()

import resend

resend.api_key = os.environ.get("RESEND_API_KEY", "").strip()

FROM_ADDRESS = os.environ.get("FROM_EMAIL", "Said By <onboarding@resend.dev>")
OPERATOR_EMAIL = os.environ.get("OPERATOR_EMAIL", "").strip()
REVIEW_UI_URL = os.environ.get("REVIEW_UI_URL", "http://localhost:8502").strip()


def _md_to_html(text: str) -> str:
    """Minimal markdown → HTML for email bodies (headings, bold, paragraphs)."""
    lines, html = text.splitlines(), []
    for line in lines:
        line = line.rstrip()
        if line.startswith("### "):
            html.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html.append(f"<h1>{line[2:]}</h1>")
        elif line == "":
            html.append("<br/>")
        else:
            line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            line = re.sub(r"\*(.+?)\*", r"<em>\1</em>", line)
            html.append(f"<p>{line}</p>")
    return "\n".join(html)


def _base_style() -> str:
    return """
    <style>
      body { font-family: Georgia, serif; max-width: 680px; margin: 0 auto; padding: 32px 24px; color: #1f2937; }
      h1 { font-size: 1.6rem; margin-bottom: 0.5rem; }
      h2 { font-size: 1.3rem; margin-top: 1.5rem; }
      h3 { font-size: 1.1rem; margin-top: 1.2rem; }
      p  { line-height: 1.7; margin: 0.6rem 0; }
      .meta { font-size: 0.8rem; color: #6b7280; margin-bottom: 2rem; border-bottom: 1px solid #e5e7eb; padding-bottom: 1rem; }
      .banner { background: #eef2ff; border: 1px solid #c7d2fe; border-radius: 6px; padding: 16px 20px; margin-bottom: 2rem; }
      .banner a { color: #4f46e5; font-weight: 600; }
      .content { border-top: 2px solid #e5e7eb; padding-top: 1.5rem; margin-top: 1.5rem; }
      .footer { font-size: 0.75rem; color: #9ca3af; margin-top: 3rem; border-top: 1px solid #f3f4f6; padding-top: 1rem; }
    </style>
    """


def send_review_email(
    *,
    client_name: str,
    client_brand_id: str,
    topic_title: str,
    content_markdown: str,
    slot_type: str = "long_blog",
) -> str:
    """Send generated content to the operator for review. Returns Resend message ID."""
    if not OPERATOR_EMAIL:
        raise ValueError("OPERATOR_EMAIL is not set in .env")

    topic_title = " ".join(topic_title.split())  # collapse any whitespace/newlines
    content_type = "Long blog" if slot_type == "long_blog" else "Short snippet"
    html_content = _md_to_html(content_markdown)

    html = f"""
    <!DOCTYPE html><html><head>{_base_style()}</head><body>
    <div class="banner">
      ✦ New content ready for review — <strong>{client_name}</strong><br/>
      <small>Log in to approve or reject: <a href="{REVIEW_UI_URL}">{REVIEW_UI_URL}</a></small>
    </div>
    <div class="meta">
      <strong>Client:</strong> {client_name} &nbsp;·&nbsp;
      <strong>Type:</strong> {content_type} &nbsp;·&nbsp;
      <strong>Brand:</strong> {client_brand_id}
    </div>
    <h1>{topic_title}</h1>
    <div class="content">
      {html_content}
    </div>
    <div class="footer">
      Generated by Content Factory · Reply to this email or visit the UI to approve.
    </div>
    </body></html>
    """

    params: resend.Emails.SendParams = {
        "from": FROM_ADDRESS,
        "to": [OPERATOR_EMAIL],
        "subject": f"[Review] {topic_title} — {client_name}",
        "html": html,
    }
    response = resend.Emails.send(params)
    return response["id"]


def send_new_submission_email(*, submission: dict) -> str:
    """Notify operator that a new client intake was submitted."""
    if not OPERATOR_EMAIL:
        raise ValueError("OPERATOR_EMAIL is not set in .env")

    name = submission.get("client_name", "Unknown")
    email = submission.get("client_email", "")
    role = submission.get("brand_archetype", "").replace("_", " ").title()
    about = submission.get("about", "")
    review_url = f"{REVIEW_UI_URL}/admin"

    html = f"""
    <!DOCTYPE html><html><head>{_base_style()}</head><body>
    <div class="banner">
      ✦ New client intake submitted<br/>
      <small>Review and activate at: <a href="{review_url}">{review_url}</a></small>
    </div>
    <h2 style="margin-top:0">{name}</h2>
    <div class="meta">
      <strong>Email:</strong> {email} &nbsp;·&nbsp;
      <strong>Role:</strong> {role}
    </div>
    <p><strong>What they write about:</strong><br/>{about}</p>
    <div class="footer">Content Factory · New submission notification</div>
    </body></html>
    """

    params: resend.Emails.SendParams = {
        "from": FROM_ADDRESS,
        "to": [OPERATOR_EMAIL],
        "subject": f"New intake: {name}",
        "html": html,
    }
    response = resend.Emails.send(params)
    return response["id"]


def send_delivery_email(
    *,
    client_name: str,
    client_email: str,
    topic_title: str,
    content_markdown: str,
    slot_type: str = "long_blog",
) -> str:
    """Send approved content to the client. Returns Resend message ID.

    In sandbox mode (no custom domain), Resend only allows sending to the
    operator's own address. We route there with a forwarding note.
    """
    if not client_email:
        raise ValueError("client_email is empty")

    topic_title = " ".join(topic_title.split())
    # Sandbox = still on resend.dev address; custom domain = send direct to client
    sandbox = "resend.dev" in FROM_ADDRESS
    to_address = OPERATOR_EMAIL if sandbox else client_email
    html_content = _md_to_html(content_markdown)

    sandbox_banner = ""
    if sandbox:
        sandbox_banner = f"""
        <div style="background:#fef3c7;border:1px solid #fcd34d;border-radius:6px;padding:12px 16px;margin-bottom:24px;font-size:0.8rem;color:#92400e;">
          <strong>Sandbox mode</strong> — This would be sent to <strong>{client_email}</strong>.
          Forward manually or verify a domain at resend.com/domains to send directly.
        </div>"""

    html = f"""
    <!DOCTYPE html><html><head>{_base_style()}</head><body>
    {sandbox_banner}
    <h1>{topic_title}</h1>
    <div class="content">
      {html_content}
    </div>
    <div class="footer">
      Delivered by Content Factory · For: {client_name} ({client_email})
    </div>
    </body></html>
    """

    params: resend.Emails.SendParams = {
        "from": FROM_ADDRESS,
        "to": [to_address],
        "subject": f"[{client_name}] {topic_title}" if sandbox else topic_title,
        "html": html,
    }
    response = resend.Emails.send(params)
    return response["id"]
